### ISSUE TITLE
Command unregisteration does not work

### ISSUE THREAD

**Issue by soshimee** [JorelAli/CommandAPI#339] opened 2022-09-19 12:32 UTC
### CommandAPI version

8.5.1

### Minecraft version

1.19.2

### Are you shading the CommandAPI?

No

### What I did

- https://commandapi.jorel.dev/8.5.1/reloading.html

### What actually happened

The command never unregisters when disabling the plugin using reload or another plugin.

### What should have happened

It should unregister properly and disappear.

**Comment by DerEchtePilz** [comment] 2022-09-19 12:52
As far as I am aware, disabling should also work with vanilla commands, right?
For example, if I have something like this: `CommandAPI.unregister("reload");`, it should unload all `reload`-commands.
Because if it does, this has nothing to do with ServerUtils, but is a CommandAPI issue.

**Comment by DerEchtePilz** [comment] 2022-09-27 16:14
> > As far as I am aware, disabling should also work with vanilla commands, right? For example, if I have something like this: `CommandAPI.unregister("reload");`, it should unload all `reload`-commands. Because if it does, this has nothing to do with ServerUtils, but is a CommandAPI issue.
> 
> Yes, this should work for (almost) any vanilla command. There are a few vanilla commands that are exempt from this (not sure about /reload, but I think /help is exempt).
> 
> The reason I mentioned ServerUtils is because ServerUtils has the functionality to disable a plugin, whereas calling `/reload` disables a plugin (and presumably unregisters it) and then enables the plugin (which would re-register it)

I tested this with the `gamemode` command and it got disabled. Seems like you literally cannot disable `/reload` which is sad.

**Comment by zmatez** [comment] 2022-11-29 19:05
/help does not want to be unregistered, but for example /kick works

**Comment by JorelAli** [comment] 2022-11-30 14:43
> /help does not want to be unregistered, but for example /kick works

If I recall, there are a few commands which are "immune" to being unregistered, as stated here:

> Yes, this should work for (almost) any vanilla command. There are a few vanilla commands that are exempt from this (not sure about /reload, but I think /help is exempt).

**Comment by DerEchtePilz** [comment] 2023-09-01 21:31
@soshimee 
Recently, CommandAPI v9.1.0 was released. In this version, changes to the command unregistration system were made.
If you use 9.1.0, does this issue still persist?

**Comment by opl-** [comment] 2023-10-05 23:51
I had a conversation about what could be the same issue on Discord today ([link](https://discord.com/channels/745416925924032523/745418840153784401/1159585104356712551)). In my case it was caused by not calling `onLoad` when shading CommandAPI v9.2.0 in my plugin (see [here](https://commandapi.jorel.dev/9.2.0/setup_shading.html#shading-requirements)).

Using exactly the same code but running CommandAPI v9.0.3 instead of v9.2.0 makes it fail to unregister the command again.

**Comment by DerEchtePilz** [comment] 2023-10-06 19:21
@soshimee 
Just tested your setup with CommandAPI 9.2.0, Minecraft 1.20.1, and used ServerUtils to disable the test plugin.
I used this code to register the command:
```java
new CommandAPICommand("ping")
            .executes((sender, args) -> {
                sender.sendMessage("Pong!");
            })
            .register();
```

I used this code to unregister the command:
```java
CommandAPI.unregister("ping");
```
After running `/serverutils disableplugin BugTestingCommandAPI`, the `ping` command did no longer exist.

Closing this for now, if any further issues appear, please reply to this!

**Closed by DerEchtePilz** 2023-10-06 19:21 UTC
Labels: bug
