### ISSUE TITLE
Reloading with PlugManX doesn't work at all

### ISSUE THREAD

**Issue by xLexih** [JorelAli/CommandAPI#527] opened 2024-03-11 12:12 UTC
### CommandAPI version

9.3.0

### Minecraft version

1.20.1

### Are you shading the CommandAPI?

Yes

### What I did

I setup a 1.20.2 paper server with [PlugmanX](https://github.com/TheBlackEntity/PlugManX) and my own plugin with the following:

```kt
override fun onLoad() {
    instance = this
    CommandAPI.onLoad(CommandAPIBukkitConfig(this)
    .missingExecutorImplementationMessage("You cannot execute this command!")
    .dispatcherFile(File(dataFolder, "command_registration.json")));
}
 override fun onEnable() {
    CommandAPI.onEnable()
    CommandAPICommand("testreregistration")
      .withArguments(StringArgument("testString"))
      .withArguments(LiteralArgument.of("success"))
      .executes(CommandExecutor { executor, args ->
        val testString: String = args.get("testString") as String
        executor.sendMessage(Component.text("The test String was: '" + testString + "'"));
      }).register();
}
override fun onDisable() {
    CommandAPI.unregister("testreregistration", true)
    CommandAPI.onDisable()
}
```

server starts up normally but using `/plugman reload <plugin>` causes the issue

### What actually happened

When the server starts up normally the command works fine, but once you run `/plugman reload <plugin>` the plugin reloads and if the command was unregistered in `onDisable()` the command disappears and never gets registered again.

### What should have happened

It should unregister and register the command similar to how `/reload confirm` does it

**Comment by TheBlackEntity** [comment] 2024-03-11 17:27
> I've been digging around in PlugManX's source and it should be totally their fault. They assume that every command is added by a plugin as far as my quick analysis goes. With added by a plugin, I mean by using the well known method that Bukkit added and not using a command framework. The commands registered by the CommandAPI do not pass a check if they are `PluginCommand`s since we do not use the `BukkitPluginCommand` class. I believe this issue should also be opened on their GitHub which you linked to make them aware of commands that do not have plugins associated with them.
> 
> The main issue seems to be their [BukkitCommandWrap](https://github.com/TheBlackEntity/PlugManX/blob/master/src/main/java/com/rylinaux/plugman/util/BukkitCommandWrap.java) class which seems to only load commands that are wrapped with a `BukkitCommandWrapper`. The CommandAPI, however, uses the `VanillaCommandWrapper` class and from my quick analysis, PlugManX does not reload these commands. It is possible that I have missed something, but opening this on their GitHub too would certainly not be a bad idea.

Well, as long as my BukkitCommandWrapper doesn't somehow delete the command, there shouldn't be any issues actually registering the command.

Commands using `VanillaCommandWrapper` should also get properly loaded since I'm also calling `CraftServer#syncCommands` shortly after.

(Which probably makes the rest of my BukkitCommandWrapper setup useless)

**Comment by DerEchtePilz** [comment] 2024-03-11 17:34
@TheBlackEntity 
Whether it's your command wrapper class or not, the plugin causing this issue definitely is your plugin since reloading using the built-in /reload command works without issues (well, if you're not considering it's already flawed nature that is).
I can probably spend some time tomorrow and investigate this issue further and see what causes what. I can also probably try some more scenarios and see if other setups work while others don't.
However, right now I am fairly confident that your plugin causes this issue.

**Comment by DerEchtePilz** [comment] 2024-03-12 09:36
> I'm also unsure what's going on with the command map in unloadCommands...

Just so you know, I was talking about the `commands` field.

**Comment by DerEchtePilz** [comment] 2024-08-16 06:40
I think I am gonna close this issue as this is nothing caused by the CommandAPI but rather is caused by the already flawed concept of reloading plugins at runtime.

**Closed by DerEchtePilz** 2024-08-16 06:40 UTC
Labels: bug
