### ISSUE TITLE
Crash when executing any commands after /reload

### ISSUE THREAD

**Issue by Propromp** [JorelAli/CommandAPI#209] opened 2021-06-02 07:36 UTC
# CommandAPI version
5.12(shade)

# server
This server is running Purpur version git-Purpur-1047 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 109 version(s) behind

# error message
```
[16:24:01 INFO]: ** issued server command: /gamemode spectator
[16:24:01 INFO]: [**: Set own game mode to Spectator Mode]
[16:24:07 INFO]: **issued server command: /gamemode creative
[16:24:07 INFO]: [**: Set own game mode to Creative Mode]
[16:24:11 INFO]: **issued server command: /gamemode spectator4
[16:24:13 INFO]: **issued server command: /gamemode spectator
[16:24:13 INFO]: [**: Set own game mode to Spectator Mode]
[16:24:19 INFO]: **issued server command: /gamemode creative
[16:24:19 INFO]: [**: Set own game mode to Creative Mode]
[16:24:35 INFO]: **issued server command: /effect give **minecraft:invisibility 10000 10 true
[16:24:35 INFO]: [**: Applied effect Invisibility to **]
[16:25:04 ERROR]: Encountered an unexpected exception
java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
        at dev.jorel.commandapi.arguments.Argument.fromSuggestions(Argument.java:87) ~[?:?]
        at dev.jorel.commandapi.arguments.Argument.lambda$overrideSuggestions$3(Argument.java:127) ~[?:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$toSuggestions$17(CommandAPIHandler.java:824) ~[?:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.5.jar:git-Purpur-1047]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:597) ~[patched_1.16.5.jar:git-Purpur-1047]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:847) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1047]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:823) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:510) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:465) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:145) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:123) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1047]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 18 more
[16:25:04 ERROR]:       Cause of unexpected exception was
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:823) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:510) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:465) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:145) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:123) ~[patched_1.16.5.jar:git-Purpur-1047]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1047]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at dev.jorel.commandapi.arguments.Argument.fromSuggestions(Argument.java:87) ~[?:?]
        at dev.jorel.commandapi.arguments.Argument.lambda$overrideSuggestions$3(Argument.java:127) ~[?:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$toSuggestions$17(CommandAPIHandler.java:824) ~[?:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.5.jar:git-Purpur-1047]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:597) ~[patched_1.16.5.jar:git-Purpur-1047]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:847) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1047]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1047]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[16:25:04 ERROR]: This crash report has been saved to: /app/./crash-reports/crash-2021-06-02_16.25.04-server.txt
```

**Comment by Propromp** [comment] 2021-06-02 07:37
** is a Player name

**Comment by JorelAli** [comment] 2021-06-02 07:58
This should be fixed in 6.0.0 due to changes with regards to how suggestions are populated internally. I'll make sure to double check that this works before releasing.

**Comment by JorelAli** [comment] 2021-06-02 17:35
@Propromp I could not reproduce the original issue that you've raised.

Here's what I did:
- Installed a Purpur 1.16.5 server:
```
This server is running Purpur version git-Purpur-1156 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-638 (MC: 1.16.5)
```
- Shaded CommandAPI 5.12 using the following code:
```java
import org.bukkit.plugin.java.JavaPlugin;

import dev.jorel.commandapi.CommandAPI;
import dev.jorel.commandapi.CommandAPIConfig;

public class Main extends JavaPlugin {
	
	@Override
	public void onLoad() {
		CommandAPI.onLoad(new CommandAPIConfig());
	}
	
	@Override
	public void onEnable() {
		CommandAPI.onEnable(this);
	}

}
  ```
- Ran the command `/effect give Skepter minecraft:invisibility 10000 10 true`

Everything worked perfectly on my machine and I could not get any errors to appear. Did you register any commands with the CommandAPI or unregister any vanilla commands?

**Comment by Propromp** [comment] 2021-06-03 06:55
Here is my command registration code. -> https://github.com/Propromp/SurvivalRoyale/blob/main/src/main/kotlin/net/propromp/survivalroyale/command/SurvivalRoyaleCommand.kt
I did not unregister any vanilla commands.

**Comment by Propromp** [comment] 2021-06-04 22:54
I found that this issue does not happen in version 5.7

**Comment by Propromp** [comment] 2021-06-13 10:18
I have found that this problem occurs when the command is run after the server has been reloaded. I also found that it actually occurs in version 5.7.

**Comment by JorelAli** [comment] 2021-06-13 12:02
The CommandAPI does not support server reloading:
https://commandapi.jorel.dev/5.12/troubleshooting.html#serverplugin-reloading

**Closed** 2022-04-27 11:08 UTC
Labels: bug

**Comment by MC-XiaoHei** [comment] 2024-02-03 07:41
In essence, this problem can be solved by re-entering the server
