### ISSUE TITLE
Reloading server with person in it throws asynchronous access exception for PlayerCommandSendEvent

### ISSUE THREAD

**Issue by blubbarbs** [JorelAli/CommandAPI#316] opened 2022-08-03 18:23 UTC
### CommandAPI version

8.5.0

### Minecraft version

1.19

### Are you shading the CommandAPI?

No

### What I did

To reproduce:

1. Install ComandAPI v 8.5.0 into the spigot plugins folder. No other plugins are necessary.
2. Run the server with a clean world (no data packs in it except the default bukkit one).
3. Join the server with your account.
4. Reload the server.

### What actually happened

The console throws out an error when reloading the datapacks. As stated above, there aren't even any data packs in the world besides the one that Spigot automatically inserts.

### What should have happened

The datapacks should reload without error.

### Server logs and CommandAPI config

verbose-output is set to true for the config
[latest.log](https://github.com/JorelAli/CommandAPI/files/9254070/latest.log)

**Comment by JorelAli** [comment] 2022-08-03 18:29
This appears to be caused by the [`syncCommands` NMS call](https://github.com/JorelAli/CommandAPI/blob/f6d72b7f8fb195563b7275fa5152ec9d7c53550f/commandapi-nms/commandapi-1.19/src/main/java/dev/jorel/commandapi/nms/NMS_1_19_R1.java#L842), which (I presume) handles some sort of vanilla command reloading.

It'll take some time to stare at this (running it in a sync task may simply save it, but we'll find out during testing). If it's a quick fix, I'll schedule this for the upcoming 8.5.1 release which already has a handful of fixes in it.

**Comment by JorelAli** [comment] 2022-08-04 10:14
It's worth noting that this issue cannot be reproduced on Paper and appears to be a Spigot-specific issue.

**Comment by JorelAli** [comment] 2022-08-04 10:27
Fixed in 5c38cdc72c1c893e58d0c42ec12534a807373ecb, scheduled for 8.5.1's release.

**Closed** 2022-08-11 20:45 UTC
Labels: bug, implemented for next release
