### ISSUE TITLE
Custom CommandSender isn't able to run CommandAPI commands

### ISSUE THREAD

**Issue by willkroboth** [JorelAli/CommandAPI#218] opened 2021-06-16 14:58 UTC
**CommandAPI version:** _6.0.1_
Note: This also happened on version 5.12

**Minecraft version:** _1.16.5_

**What I did:**

In my plugin, I created the following class to accomplish 3 things:
1. Run commands with operator status
2. Store the result of running a command so it can be used later
3. Do all this in the background without sending messages to the console
```
import net.minecraft.server.v1_16_R3.*;
import org.bukkit.Server;
import org.bukkit.command.CommandSender;
import org.bukkit.craftbukkit.v1_16_R3.CraftWorld;
import org.bukkit.craftbukkit.v1_16_R3.command.CraftBlockCommandSender;

import java.util.Arrays;
import java.util.UUID;

// When running vanilla commands, the code wants to get a CommandListenerWrapper.
//      (in org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.class.getListener())
// When the sender is a CraftBlockCommandSender, it directly uses the getWrapper() method to do so.
// Therefore, this class extends CraftBlockCommandSender so it can easily provide a wrapper
//      The custom wrapper allows me to set shouldBroadcastCommands to false so commands don't appear in the console
//      This also means the sender is automatically an operator that can run all commands
// The class also implements ICommandListener so it can be used as one
public class OpSender extends CraftBlockCommandSender implements ICommandListener {
    private String lastMessage = "";

    private final WorldServer world;
    public OpSender(Server server) {
        // no methods in the CraftBlockCommandSender that need these values are actually used
        super(null, null);
        // this value is needed for the CommandListenerWrapper
        this.world = ((CraftWorld) server.getWorlds().get(0)).getHandle();
    }

    // Overriding getWrapper() to provide a custom CommandListenerWrapper
    public CommandListenerWrapper getWrapper() {
        // copied from the getServerCommandListener() method for net.minecraft.server.v1_16_R3.MinecraftServer.class
        return new CommandListenerWrapper(this, Vec3D.ORIGIN, Vec2F.a,
                world, 4, "OpSender", new ChatComponentText("OpSender"), world.getMinecraftServer(), null);
    }

    // provide result message
    public String getResult(){ return lastMessage; }

    // store result message for CommandSender methods
    public void sendMessage(String s) { lastMessage = s; }

    public void sendMessage(String[] strings) { lastMessage = Arrays.toString(strings); }

    public void sendMessage(UUID uuid, String s) { lastMessage = s; }

    public void sendMessage(UUID uuid, String[] strings) { lastMessage = Arrays.toString(strings); }


    // ICommandListener methods
    public void sendMessage(IChatBaseComponent iChatBaseComponent, UUID uuid) { lastMessage = iChatBaseComponent.getString(); }

    // send success and failure messages
    public boolean shouldSendSuccess() { return true; }

    public boolean shouldSendFailure() { return true; }

    // do not broadcast commands to console
    public boolean shouldBroadcastCommands() { return false; }

    // not used
    public CommandSender getBukkitSender(CommandListenerWrapper commandListenerWrapper) { return null; }
}
```
It's kind of a mess to understand, but it seems to work how I want with vanilla commands. However, when I use it to run commands registered with the CommandAPI, it just sends back the message: "You must be a commandsender to run this command."

**What should have happened:**
A command registered with the CommandAPI should run normally

**Additional Context**
- To run a command with the OpSender class, I use:
```
Server server = Bukkit.getServer();
OpSender sender = new OpSender(server);
server.dispatchCommand(sender, "command");
```
- This problem looks similar to #105, which was supposedly fixed in version 3.1, so it could totally be a problem with my class

**Comment by JorelAli** [comment] 2021-06-16 16:52
This should now be fixed in 6.0.3. I'll leave this issue for you to close @willkroboth (if for some reason, my fix in 6.0.3 doesn't fix it, then please let me know!)

**Comment by willkroboth** [comment] 2021-06-16 17:14
It seems like there is still a problem. I now get this:
`[13:07:58 INFO]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.sendMessage(String)" because "sender" is null
[13:07:58 INFO]: 	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.run_return(ConfigCommandExecutor.java:958)
[13:07:58 INFO]: 	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.execute(ConfigCommandExecutor.java:867)
[13:07:58 INFO]: 	at dev.jorel.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:113)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:306)
[13:07:58 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[13:07:58 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:268)
[13:07:58 INFO]: 	at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[13:07:58 INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:07:58 INFO]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[13:07:58 INFO]: 	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.run_command(ConfigCommandExecutor.java:890)
[13:07:58 INFO]: 	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.run_set(ConfigCommandExecutor.java:916)
[13:07:58 INFO]: 	at me.willkroboth.ConfigCommands.ConfigCommandExecutor.execute(ConfigCommandExecutor.java:855)
[13:07:58 INFO]: 	at dev.jorel.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:113)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
[13:07:58 INFO]: 	at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:306)
[13:07:58 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[13:07:58 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:268)
[13:07:58 INFO]: 	at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[13:07:58 INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:07:58 INFO]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[13:07:58 INFO]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:07:58 INFO]: 	at java.base/java.lang.Thread.run(Thread.java:831)
`
It seems like it is running the command, but it's passing in the sender as null, so ends up throwing a NullPointerException when trying to do sender.sendMessage("message").

**Comment by JorelAli** [comment] 2021-06-16 17:29
I couldn't reproduce the error you've described.

```java
// When running vanilla commands, the code wants to get a CommandListenerWrapper.
//      (in org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.class.getListener())
// When the sender is a CraftBlockCommandSender, it directly uses the getWrapper() method to do so.
// Therefore, this class extends CraftBlockCommandSender so it can easily provide a wrapper
//      The custom wrapper allows me to set shouldBroadcastCommands to false so commands don't appear in the console
//      This also means the sender is automatically an operator that can run all commands
// The class also implements ICommandListener so it can be used as one
class OpSender extends CraftBlockCommandSender implements ICommandListener {
    private String lastMessage = "";

    private final WorldServer world;
    public OpSender(Server server) {
        // no methods in the CraftBlockCommandSender that need these values are actually used
        super(null, null);
        // this value is needed for the CommandListenerWrapper
        this.world = ((CraftWorld) server.getWorlds().get(0)).getHandle();
    }

    // Overriding getWrapper() to provide a custom CommandListenerWrapper
    public CommandListenerWrapper getWrapper() {
        // copied from the getServerCommandListener() method for net.minecraft.server.v1_16_R3.MinecraftServer.class
        return new CommandListenerWrapper(this, Vec3D.ORIGIN, Vec2F.a,
                world, 4, "OpSender", new ChatComponentText("OpSender"), world.getMinecraftServer(), null);
    }

    // provide result message
    public String getResult(){ return lastMessage; }

    // store result message for CommandSender methods
    public void sendMessage(String s) { lastMessage = s; }

    public void sendMessage(String[] strings) { lastMessage = Arrays.toString(strings); }

    public void sendMessage(UUID uuid, String s) { lastMessage = s; }

    public void sendMessage(UUID uuid, String[] strings) { lastMessage = Arrays.toString(strings); }


    // ICommandListener methods
    public void sendMessage(IChatBaseComponent iChatBaseComponent, UUID uuid) { lastMessage = iChatBaseComponent.getString(); }

    // send success and failure messages
    public boolean shouldSendSuccess() { return true; }

    public boolean shouldSendFailure() { return true; }

    // do not broadcast commands to console
    public boolean shouldBroadcastCommands() { return false; }

    // not used
    public CommandSender getBukkitSender(CommandListenerWrapper commandListenerWrapper) { return null; }
}

new CommandAPICommand("command")
	.executes((sender, args) -> {
		System.out.println("CMD");
	})
	.register();

new CommandAPICommand("runall")
	.executes((oldsender, args) -> {
		System.out.println(oldsender);
		System.out.println(Arrays.deepToString(args));
		Server server = Bukkit.getServer();
		OpSender sender = new OpSender(server);
		server.dispatchCommand(sender, "command");
	})
	.register();
```

Using the above code, I get the following result, which shows that the sender is not `null`:
```
runall
[18:28:03 INFO]: com.destroystokyo.paper.console.TerminalConsoleCommandSender@3d4ebdd1
[18:28:03 INFO]: []
[18:28:03 INFO]: CMD
```

**Comment by willkroboth** [comment] 2021-06-16 17:32
Try putting `sender.sendMessage("CMD");` instead of `System.out.println("CMD");` in the "command" command.

**Comment by JorelAli** [comment] 2021-06-16 17:32
Yup, I just realized that :P

**Comment by JorelAli** [comment] 2021-06-16 17:42
After putting print statements all over my code and using `Thread.dumpStack()`, I found the root cause:
```java
// not used
public CommandSender getBukkitSender(CommandListenerWrapper commandListenerWrapper) { return null; }
```

The CommandAPI needs to return a `CommandSender` instance. The only way to get this is from `getBukkitSender()`. You literally return null, hence why you get null.

**Comment by willkroboth** [comment] 2021-06-16 17:44
Thanks, I didn't see that! I can't fix it on my end right now, but it will likely work after fixing that.

**Closed** 2021-06-16 20:43 UTC
Labels: bug
